//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource-ar", typeof(Resource_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجرات.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل .
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة طالب جديد.
        /// </summary>
        internal static string AddNewStudent {
            get {
                return ResourceManager.GetString("AddNewStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظة - اللواء - القرية أو الحي.
        /// </summary>
        internal static string AddressPlaceHolder {
            get {
                return ResourceManager.GetString("AddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  غير متوفر ، يرجى تجربة اسم مستخدم آخر !!!.
        /// </summary>
        internal static string AlreadyTaken {
            get {
                return ResourceManager.GetString("AlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صباحاً.
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافقة.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع الى القائمة.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة السر الخاصة بي.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلد الإقامة.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الدفعة الحالي.
        /// </summary>
        internal static string CurrentWaveNumber {
            get {
                return ResourceManager.GetString("CurrentWaveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم .
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايقاف.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى التعليمي.
        /// </summary>
        internal static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني مستخدم سابقاً.
        /// </summary>
        internal static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثى.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الاول.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول مطلوب .
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل نسيت كلمة السر؟.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرسان.
        /// </summary>
        internal static string Fursan {
            get {
                return ResourceManager.GetString("Fursan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع تعريفي لبرنامج (فرسان).
        /// </summary>
        internal static string FursanVideo {
            get {
                return ResourceManager.GetString("FursanVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحنس.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظة.
        /// </summary>
        internal static string Hafazah {
            get {
                return ResourceManager.GetString("Hafazah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع تعريفي لبرنامج (حفظة).
        /// </summary>
        internal static string HafazahVideo {
            get {
                return ResourceManager.GetString("HafazahVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء التحقق من وجود واتس أب للرقم.
        /// </summary>
        internal static string IncludeWhatsApp {
            get {
                return ResourceManager.GetString("IncludeWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضوية شيخ جديدة.
        /// </summary>
        internal static string InstructorMember {
            get {
                return ResourceManager.GetString("InstructorMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموعد المناسب للمقابلة.
        /// </summary>
        internal static string InterviewDate {
            get {
                return ResourceManager.GetString("InterviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة.
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف عرفت عن البرنامج؟.
        /// </summary>
        internal static string KnownFrom {
            get {
                return ResourceManager.GetString("KnownFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الاخير.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشيخ.
        /// </summary>
        internal static string LinkInstrcutor {
            get {
                return ResourceManager.GetString("LinkInstrcutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تـسجيل الدخول.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة خيارات البلدان.
        /// </summary>
        internal static string ManageCountriesOptions {
            get {
                return ResourceManager.GetString("ManageCountriesOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة خيارات مستويات التعليم.
        /// </summary>
        internal static string ManageEducationLevelsOptions {
            get {
                return ResourceManager.GetString("ManageEducationLevelsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستويات.
        /// </summary>
        internal static string ManageLevels {
            get {
                return ResourceManager.GetString("ManageLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المسارات.
        /// </summary>
        internal static string ManagePaths {
            get {
                return ResourceManager.GetString("ManagePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المراحل.
        /// </summary>
        internal static string ManagePhases {
            get {
                return ResourceManager.GetString("ManagePhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة خيارات حفظ القرآن.
        /// </summary>
        internal static string ManageQuranMemorizedsOptions {
            get {
                return ResourceManager.GetString("ManageQuranMemorizedsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة عضويات المشايخ.
        /// </summary>
        internal static string ManageSheikhsMemberships {
            get {
                return ResourceManager.GetString("ManageSheikhsMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير محدد.
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات اخرى.
        /// </summary>
        internal static string OtherDetails {
            get {
                return ResourceManager.GetString("OtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسار.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات المعلقة.
        /// </summary>
        internal static string PendingRequests {
            get {
                return ResourceManager.GetString("PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مستخدم سابقاً.
        /// </summary>
        internal static string PhoneAlreadyUsed {
            get {
                return ResourceManager.GetString("PhoneAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ملء جميع المعلومات للانضمام.
        /// </summary>
        internal static string PleaseFillInfotoJoin {
            get {
                return ResourceManager.GetString("PleaseFillInfotoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساءً.
        /// </summary>
        internal static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات البرنامج.
        /// </summary>
        internal static string ProgramSettings {
            get {
                return ResourceManager.GetString("ProgramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرنامج.
        /// </summary>
        internal static string ProgramType {
            get {
                return ResourceManager.GetString("ProgramType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ القراًن.
        /// </summary>
        internal static string QuranMemorized {
            get {
                return ResourceManager.GetString("QuranMemorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعضاء المسجلين.
        /// </summary>
        internal static string RegisteredMembers {
            get {
                return ResourceManager.GetString("RegisteredMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل عضو جديد.
        /// </summary>
        internal static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات التسجيل.
        /// </summary>
        internal static string RegistrationSettings {
            get {
                return ResourceManager.GetString("RegistrationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل متوقف الان هل تريد بدء عمله.
        /// </summary>
        internal static string RegistrationStatusOff {
            get {
                return ResourceManager.GetString("RegistrationStatusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل مفتوح الان هل تريد إيقاف عمله.
        /// </summary>
        internal static string RegistrationStatusOn {
            get {
                return ResourceManager.GetString("RegistrationStatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * مطلوب.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث برقم الهاتف.
        /// </summary>
        internal static string SearchPhoneNumber {
            get {
                return ResourceManager.GetString("SearchPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الثاني.
        /// </summary>
        internal static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون كلمة المرور على الاٌقل 6 خانات .
        /// </summary>
        internal static string ShouldBeAtLeast6Digits {
            get {
                return ResourceManager.GetString("ShouldBeAtLeast6Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار الاعضاء فقط الذين هم.
        /// </summary>
        internal static string ShowMembers {
            get {
                return ResourceManager.GetString("ShowMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا , التسجيل مغلق .
        /// </summary>
        internal static string SorryTheRegistrationClosed {
            get {
                return ResourceManager.GetString("SorryTheRegistrationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string SuggestPassword {
            get {
                return ResourceManager.GetString("SuggestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم عملية التسجيل بنجاح .. سوف يتم التواصل معك قريبا.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثالث.
        /// </summary>
        internal static string ThirdName {
            get {
                return ResourceManager.GetString("ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  اسم المستخدم متوفر !.
        /// </summary>
        internal static string UsernameIsAvailable {
            get {
                return ResourceManager.GetString("UsernameIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات المستخدمين .
        /// </summary>
        internal static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدفعة - التسلسل.
        /// </summary>
        internal static string WaveNumber {
            get {
                return ResourceManager.GetString("WaveNumber", resourceCulture);
            }
        }
    }
}
