// <auto-generated />
namespace Hafazah.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddWaveNumberColumnToMember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWaveNumberColumnToMember));
        
        string IMigrationMetadata.Id
        {
            get { return "202212311650236_AddWaveNumberColumnToMember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
