// <auto-generated />
namespace Hafazah.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddLevelTableWithRelationShips : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLevelTableWithRelationShips));
        
        string IMigrationMetadata.Id
        {
            get { return "202209192236203_AddLevelTableWithRelationShips"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
